/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moduletest;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class App {
    @GetMapping("/hello")
    public String sayHello() {
        return "hello_world";
    }
}
